#!/bin/sh

# PROVIDE: LevoCoin
# REQUIRE: LOGIN
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# LevoCoin_enable (bool): Set to NO by default. Set this variable to YES if you want to enable LevoCoin service.
# LevoCoin_config (path): Set to /usr/local/etc/LevoCoin.conf by default.
# LevoCoin_user:  The user account LevoCoin daemon runs as. It uses 'root' user by default.
# LevoCoin_group: The group account LevoCoin daemon runs as. It uses 'wheel' group by default.
# LevoCoin_datadir (str): Default to "/var/db/LevoCoin". Base data directory.

. /etc/rc.subr

name=LevoCoin
rcvar=LevoCoin_enable

: ${LevoCoin_enable:=NO}
: ${LevoCoin_config=/usr/local/etc/LevoCoin.conf}
: ${LevoCoin_datadir=/var/db/LevoCoin}
: ${LevoCoin_user="root"}
: ${LevoCoin_group="wheel"}

required_files=${LevoCoin_config}
command=/usr/local/bin/LevoCoind
LevoCoin_chdir=${LevoCoin_datadir}
pidfile="${LevoCoin_datadir}/LevoCoind.pid"
stop_cmd=LevoCoin_stop
command_args="-conf=${LevoCoin_config} -datadir=${LevoCoin_datadir} -daemon -pid=${pidfile}"
start_precmd="${name}_prestart"

LevoCoin_create_datadir()
{
	echo "Creating data directory"
	eval mkdir -p ${LevoCoin_datadir}
	[ $? -eq 0 ] && chown -R ${LevoCoin_user}:${LevoCoin_group} ${LevoCoin_datadir}
}

LevoCoin_prestart()
{
	if [ ! -d "${LevoCoin_datadir}/." ]; then
		LevoCoin_create_datadir || return 1
	fi
}

LevoCoin_requirepidfile()
{
	if [ ! "0`check_pidfile ${pidfile} ${command}`" -gt 1 ]; then
		echo "${name} not running? (check $pidfile)."
		exit 1
	fi
}

LevoCoin_stop()
{
    LevoCoin_requirepidfile

	echo "Stopping ${name}."
	eval ${command} -conf=${LevoCoin_config} -datadir=${LevoCoin_datadir} stop
	wait_for_pids ${rc_pid}
}

load_rc_config $name
run_rc_command "$1"
